# Generated by Django 4.1.13 on 2025-07-23 13:52

import EhospitalityApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EhospitalityApp', '0003_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(default=EhospitalityApp.models.default_appointment_time),
        ),
        migrations.AddField(
            model_name='patient',
            name='bloodgroup',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('U', 'Unknown')], default='U', max_length=3),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default='unknown@example.com', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('U', 'Unknown')], default='U', max_length=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirm', 'confirm'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
