# Generated by Django 4.1.13 on 2025-07-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EhospitalityApp', '0005_appointment_fee_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='fee',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1234, max_digits=8),
            preserve_default=False,
        ),
    ]
